plugins:
  - jekyll-feed

title: Short Stories by Lucid Illusions
email: gmail@lucidillusions.in
description: >- # this means to ignore newlines until "baseurl:"
  This is a blog compiling all the stories from the prompts received on bluesky.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ss.lucidillusions.in" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lucidillusions_
instagram_username: lucidillusions.in
google_analytics: G-61GWSJVEWN

# author: "Lucid Illusions"

# Build settings
sass:
  sass_dir: _sass
include: ["_pages"]
collections:
  blogs:
    output: true
    permalink: /blog/:path/ # Define URL structure for individual blogs

kramdown:
  input: GFM

# Webmention.io plugin configuration
webmention:
  username: ss.lucidillusions.in
