plugins:
  #  - jekyll-feed
  - jekyll-webmention_io

title: Short Stories by Lucid Illusions
email: gmail@lucidillusions.in
description: >- # this means to ignore newlines until "baseurl:"
  This website is a collection of my short stories.

url: "https://ss.lucidillusions.in"
baseurl: ""
twitter_username: lucidillusions_
instagram_username: lucidillusions.in
google_analytics: G-61GWSJVEWN

# author: "Lucid Illusions"

# Build settings
sass:
  sass_dir: _sass
include: ["_pages", "_plugins"]
collections:
  blogs:
    output: true
    permalink: /blog/:path/ # Define URL structure for individual blogs

kramdown:
  input: GFM

# Webmention.io plugin configuration
webmention:
  username: ss.lucidillusions.in

# Enable comments by default for all posts (you can override this per post)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true # Set to true to enable comments on posts by default
      # You'll also need a 'layout: post' if you're not using Minimal Mistakes' 'single'
      # Make sure your post layout calls {{ content }} for the post body.

comments:
  provider: "custom" # This tells Jekyll you're using a custom comment system

#feed:
#  collections:
#    posts:
#      path: "/feed.xml"
#    blogs:
#      path: "/feed.xml"
#  tags: false
#  categories: false
#  posts_limit: 10
#  excerpt_only: true

timezone: Asia/Kolkata
