name: Build and Deploy Jekyll with Webmentions

on:
  push:
    branches:
      - main # Trigger on pushes to your main content branch (e.g., master, main)
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Change this line:
          ruby-version: '3.3.0' # Choose a specific version like '3.3.0', '3.2.0', or '3.2.5' from the list
          bundler-cache: true # Installs gems specified in Gemfile.lock

      - name: Cache Jekyll
        uses: actions/cache@v4
        with:
          path: |
            _site
            .jekyll-cache
            .webmention-cache
          key: ${{ runner.os }}-jekyll-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-jekyll-

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build

      - name: Send Outgoing Webmentions
        run: |
          bundle exec jekyll webmention
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
          keep_files: false
          # cname: ss.lucidillusions.in
