name: Build and Deploy Jekyll with Webmentions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.0"
          # Temporarily disable bundler-cache to force fresh install and better debug
          bundler-cache: false # COMMENT OUT OR REMOVE THIS LINE

      - name: Install Ruby Gems (verbose output)
        run: |
          bundle install --verbose

      - name: Debug - List installed Ruby Gems
        run: |
          bundle list --name-only | grep jekyll-webmention_io || echo "jekyll-webmention_io not found by bundle list"
          echo "Full bundle list:"
          bundle list

      # Remove the old cache step if it was there and you want to truly force no cache.
      # Or, keep it but ensure path and key are correct. For debugging, it's simpler to remove for now.
      # If you keep it, make sure 'path' includes 'vendor/bundle' if you're installing into there.
      - name: Cache Jekyll (optional during debug, can re-add later)
        uses: actions/cache@v4
        with:
          path: |
            _site
            .jekyll-cache
            .webmention-cache
            vendor/bundle # Ensure this is included if Bundler installs gems here
          key: ${{ runner.os }}-jekyll-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-jekyll-

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build --verbose

      - name: Send Outgoing Webmentions
        run: |
          bundle exec jekyll webmention
        env:
          JEKYLL_ENV: production

      - name: Debug - List contents of potential JS output directories
        run: |
          echo "Listing contents of _site/ (root of deployed site):"
          ls -la _site/ || true # '|| true' prevents error if _site is empty or problematic
          echo "" # Add a blank line for readability

          echo "Listing contents of _site/js/:"
          ls -la _site/js/ || echo "_site/js/ directory not found or empty."
          echo ""

          echo "Listing contents of _site/assets/js/:"
          ls -la _site/assets/js/ || echo "_site/assets/js/ directory not found or empty."
          echo ""

          echo "Listing contents of _site/bsky-story/js/ (just in case):"
          ls -la _site/bsky-story/js/ || echo "_site/bsky-story/js/ directory not found or empty (as expected)."
          echo ""

      #- name: Deploy to Github Pages
      #  uses: JamesIves/github-pages-deploy-action@v4
      #  with:
      #    branch: gh-pages
      #    folder: _site

      #- name: Deploy to GitHub Pages
      #  uses: peaceiris/actions-gh-pages@v4
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: _site
      #    publish_branch: gh-pages
      #   keep_files: false
      # cname: ss.lucidillusions.in

      # --- REPLACE THE MANUAL DEPLOY STEP WITH THIS FINAL, AGGRESSIVE VERSION ---

      - name: Manual Deploy to GitHub Pages (Final Diagnostic)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux # Exit immediately if a command exits with a non-zero status. Print commands and their arguments as they are executed.

          # Configure Git
          echo "--- Configuring Git ---"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory /github/workspace

          # Define deployment directory relative to the main workspace
          DEPLOY_DIR="github-pages-deploy-temp"
          rm -rf "$DEPLOY_DIR" # Clean up from previous runs if any

          echo "Temporary Git worktree directory: $DEPLOY_DIR"

          # --- Handle gh-pages branch creation if it doesn't exist ---
          echo "--- Ensuring gh-pages branch exists remotely ---"
          if ! git ls-remote --heads origin gh-pages | grep -q 'refs/heads/gh-pages'; then
              echo "gh-pages branch does not exist remotely. Creating and pushing an empty orphan branch from main workspace."

              # Temporarily switch to an orphan gh-pages branch in the main repo
              git checkout --orphan gh-pages
              git rm -rf . || true # Remove all files from the new orphan branch (clean it up)
              git commit --allow-empty -m "Initial empty gh-pages branch created by workflow" # Commit an empty state
              git push --set-upstream origin gh-pages # Push the empty branch to remote

              # Switch back to the main branch in the primary workspace
              git checkout main
              echo "Switched back to main branch in primary workspace."
              # No need for git fetch here as the next line will do it.
          else
              echo "gh-pages branch already exists remotely."
          fi

          # --- FETCH gh-pages to ensure it's fully available locally ---
          echo "--- Fetching gh-pages branch to ensure local reference is updated ---"
          git fetch origin gh-pages

          # Use git worktree for a cleaner operation. gh-pages should now exist as a valid ref.
          echo "--- Adding git worktree for gh-pages ---"
          git worktree add --force --detach "$DEPLOY_DIR" gh-pages

          # Go into the worktree
          cd "$DEPLOY_DIR"

          # --- AGGRESSIVE CLEAN AND RESET within the worktree ---
          echo "--- Aggressively cleaning and resetting worktree ---"
          git clean -fdx
          git reset --hard origin/gh-pages

          # Now copy the _site contents into the cleaned worktree
          echo "--- Copying _site contents to worktree ---"
          # Source needs to be absolute, or relative from the main workspace
          rsync -av --checksum --progress /home/runner/work/bsky-story/bsky-story/_site/. "$DEPLOY_DIR/" --exclude .git --exclude .github --exclude .ssh

          # --- CRITICAL DEBUG CHECKS AFTER RSYNC ---
          echo "--- Contents of deployment target directory AFTER rsync ---"
          ls -lR .
          echo "--- Contents of js/ directory within target after rsync ---"
          ls -l js/

          # Add, commit, and push changes
          echo "--- Adding files to git (forcing re-evaluation) ---"
          git add --all --force .

          echo "--- Git Status (final check for staged changes) ---"
          git status

          echo "--- Committing changes ---"
          if ! git diff-index --quiet HEAD; then
              git commit -m "Deploy from GitHub Actions (Aggressive Manual - ${{ github.sha }})"
          else
              echo "No changes detected to commit after rsync (this should not happen now)."
          fi

          echo "--- Pushing changes to gh-pages branch ---"
          git push --force origin gh-pages

          # Clean up temporary directory (remove the worktree)
          echo "--- Removing git worktree ---"
          cd /home/runner/work/bsky-story/bsky-story
          git worktree remove --force "$DEPLOY_DIR" || true
