# .github/workflows/update_bluesky_status.yml

name: Update Bluesky Status

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # --- IMPORTANT CHANGE HERE ---
          # Use your PAT for pushing, which will now trigger subsequent workflows.
          token: ${{ secrets.JEKYLL_BOT_TOKEN }} 

      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Run Jekyll generator to update data
        run: |
          bundle exec jekyll build --source . --destination _site_temp
        env:
          JEKYLL_ENV: production

      - name: Stage changes for commit
        run: |
          git add _data/bluesky_latest_post.yml

      - name: Check if there are changes to commit
        id: git_status_check
        run: |
          if ! git diff --cached --quiet; then
            echo "file_status=changed" >> $GITHUB_OUTPUT
            echo "Changes detected in _data/bluesky_latest_post.yml, ready to commit."
          else
            echo "file_status=no_change" >> $GITHUB_OUTPUT
            echo "No changes detected in _data/bluesky_latest_post.yml. Skipping commit."
          fi
        shell: bash

      - name: Commit and push changes
        if: steps.git_status_check.outputs.file_status == 'changed'
        run: |
          # --- IMPORTANT CHANGE HERE ---
          # Use your actual GitHub username and email for the commit,
          # as it will now be attributed to you (the PAT owner).
          git config --global user.name 'Your GitHub Username' # Replace with your actual GitHub username
          git config --global user.email 'your-email@example.com' # Replace with your actual GitHub email

          git commit -m "Automated: Update Bluesky status from latest post"
          git push
